services:
  todo:
    image: todo:go
    container_name: todo-go
    pull_policy: never
    build:
      context: ./
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongodb

  nginx:
    image: todo-nginx:alpine3.20
    container_name: todo-nginx
    pull_policy: never
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80

  mongodb:
    image: mongo:8.0.4-noble
    container_name: todo-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: todo-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false


